### ISSUE TITLE
Panic if a category's subscriptions count is greater than 36

### ISSUE THREAD

**Issue by cmollet** [TypicalAM/goread#29]
```
goread version v1.5.2
```

If a category has more than 36 subscriptions, it will trigger a runtime panic:

```
Caught panic:

list: too many items

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.20.6/libexec/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        /opt/homebrew/Cellar/go/1.20.6/libexec/src/runtime/debug/stack.go:16 +0x1c
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /Users/cory/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.2/tea.go:402 +0x8c
panic({0x1017a0260, 0x101871520})
        /opt/homebrew/Cellar/go/1.20.6/libexec/src/runtime/panic.go:890 +0x258
github.com/TypicalAM/goread/internal/ui/simplelist.(*Model).SetItems(...)
        /Users/cory/go/pkg/mod/github.com/!typical!a!m/goread@v1.5.2/internal/ui/simplelist/list.go:206
github.com/TypicalAM/goread/internal/ui/tab/category.Model.Update({0x14000498000, 0x140006be1c0, {0x14001765750, 0xe}, {{{0x1400057e1e0, 0x2, 0x2}, {{...}, {...}}, 0x0}, ...}, ...}, ...)
        /Users/cory/go/pkg/mod/github.com/!typical!a!m/goread@v1.5.2/internal/ui/tab/category/category.go:81 +0xf04
github.com/TypicalAM/goread/internal/ui/browser.Model.Update({{0x0, 0x0}, 0x1400184b3b0, {0x14000498000, {0x140018aaab0, {0x0, 0x0}}, {0x140018aaae0, {0x0, 0x0}}, ...}, ...}, ...)
        /Users/cory/go/pkg/mod/github.com/!typical!a!m/goread@v1.5.2/internal/ui/browser/browser.go:283 +0x1b74
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0x140000be370, {0x101877ed0?, 0x140000b5d40?}, 0x101067c44?)
        /Users/cory/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.2/tea.go:343 +0x584
github.com/charmbracelet/bubbletea.(*Program).Run(0x140000be370)
        /Users/cory/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.2/tea.go:465 +0x6d0
github.com/TypicalAM/goread/cmd/goread.Run()
        /Users/cory/go/pkg/mod/github.com/!typical!a!m/goread@v1.5.2/cmd/goread/goread.go:185 +0x770
github.com/TypicalAM/goread/cmd/goread.glob..func1(0x101e78a00?, {0x1014f3e1c?, 0x0?, 0x0?})
        /Users/cory/go/pkg/mod/github.com/!typical!a!m/goread@v1.5.2/cmd/goread/goread.go:44 +0x1c
github.com/spf13/cobra.(*Command).execute(0x101e78a00, {0x14000030240, 0x0, 0x0})
        /Users/cory/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x101e78a00)
        /Users/cory/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/cory/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/TypicalAM/goread/cmd/goread.Execute()
        /Users/cory/go/pkg/mod/github.com/!typical!a!m/goread@v1.5.2/cmd/goread/goread.go:73 +0x28
main.main()
        /Users/cory/go/pkg/mod/github.com/!typical!a!m/goread@v1.5.2/main.go:11 +0x64
```

Presumably because the hotkey scheme is `0-9a-z`, any category with more subscriptions than the number of available hotkeys will trigger this panic

**Comment by TypicalAM** [comment]
Thanks for pointing that out, will change soon. I guess the naming scheme for 37th and new items will be just [-] instead of panicking.

**Comment by cmollet** [comment]
Thank you, TBH I didn't even realize there were hotkeys until discovering this bug 😂 . And thank you for making a gorgeous TUI RSS reader!
