### ISSUE TITLE
Panics when pressing 'g' too many times

### ISSUE THREAD

**Issue by sigurd4** [TypicalAM/goread#55]
Pressing 'g' to cycle through links on an article crashed the program when i went from the final url.

```
Caught panic:

runtime error: index out of range [2] with length 2

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
	runtime/debug/stack.go:18 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
	github.com/charmbracelet/bubbletea@v0.23.2/tea.go:402 +0x8b
panic({0x5c7a20bfa600?, 0xc0011a48a0?})
	runtime/panic.go:785 +0x132
github.com/TypicalAM/goread/internal/ui/tab/feed.(*selector).cycle(0xc00061c228?)
	github.com/TypicalAM/goread/internal/ui/tab/feed/selector.go:103 +0x90d
github.com/TypicalAM/goread/internal/ui/tab/feed.Model.Update({{0x0, 0x1, 0x0, 0x1, 0x0, 0x1, {0x5c7a2090409d, 0x4}, {0x5c7a20906e34, 0x5}, ...}, ...}, ...)
	github.com/TypicalAM/goread/internal/ui/tab/feed/feed.go:211 +0x22e5
github.com/TypicalAM/goread/internal/ui/browser.Model.Update({{0x0, 0x0}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
	github.com/TypicalAM/goread/internal/ui/browser/browser.go:304 +0x2118
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc000152370, {0x5c7a20c4d400?, 0xc000263b08?}, 0xc000a570a0)
	github.com/charmbracelet/bubbletea@v0.23.2/tea.go:343 +0x47c
github.com/charmbracelet/bubbletea.(*Program).Run(0xc000152370)
	github.com/charmbracelet/bubbletea@v0.23.2/tea.go:465 +0x7ab
github.com/TypicalAM/goread/cmd/goread.Run()
	github.com/TypicalAM/goread/cmd/goread/goread.go:182 +0x90a
github.com/TypicalAM/goread/cmd/goread.init.func1(0xc000016100?, {0x5c7a2090f36f?, 0x7?, 0x5c7a20903f95?})
	github.com/TypicalAM/goread/cmd/goread/goread.go:44 +0x17
github.com/spf13/cobra.(*Command).execute(0x5c7a21203b60, {0xc00012a270, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x5c7a21203b60)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/TypicalAM/goread/cmd/goread.Execute()
	github.com/TypicalAM/goread/cmd/goread/goread.go:73 +0x1e
main.main()
	github.com/TypicalAM/goread/main.go:11 +0x4e
```

**Comment by TypicalAM** [comment]
Is there a chance you could provide the failing feed?

**Comment by sigurd4** [comment]
It happens to any feed if you do it on the last available entry in the feed

**Comment by TypicalAM** [comment]
Unfortunately I'm not able to reproduce neither on `kitty`/linux nor on `windows terminal`/windows on go `1.22.9`. Could you provide info like:
- `echo $TERM $LSCOLORS`
- `go version`
- `goread --version`
- Terminal emulator that you are using

**Comment by sigurd4** [comment]
$ `echo $TERM $LSCOLORS && tput cols && tput lines`:
```
xterm-kitty
105
51
```
$ `go version`
```
go version go1.23.4 linux/amd64
```
$ `goread --version`
```
goread version v1.6.5
```

I managed to reproduce it again. More info: it doesn't just happen to any feed. It happens specifically with feeds from `boards.4chan.org`. Try any board.

I'm using `kitty`.

**Comment by TypicalAM** [comment]
Solved as of `v1.7.2`, `go install github.com/TypicalAM/goread@latest`
