### ISSUE TITLE
adding a new feed panics (runtime error: invalid memory address or nil pointer dereference)

### ISSUE THREAD

**Issue by Integralist** [TypicalAM/goread#64]
👋🏻 

I tried adding this feed:
https://portal.ryce-rsp.com/feed.php

But when trying to open the feed I get:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102d5c768]

goroutine 245 [running]:
github.com/TypicalAM/goread/internal/backend/cache.SortableArticles.Less(...)
        github.com/TypicalAM/goread/internal/backend/cache/cache.go:36
sort.insertionSort({0x10354aa70, 0x14000538a98}, 0x0, 0xa)
        sort/zsortinterface.go:12 +0xbc
sort.pdqsort({0x10354aa70, 0x14000538a98}, 0x18?, 0x103463640?, 0x140000e5b01?)
        sort/zsortinterface.go:73 +0x25c
sort.Sort({0x10354aa70, 0x14000538a98})
        sort/sort.go:51 +0x60
github.com/TypicalAM/goread/internal/backend.Backend.articlesToSuccessMsg({0x140006da6f0?, 0x14000461e80?, 0x140004417b8?}, {0x14000336008, 0xa, 0x1400064c364?})
        github.com/TypicalAM/goread/internal/backend/backend.go:154 +0x5c
github.com/TypicalAM/goread/internal/backend.Backend.FetchArticles-fm.Backend.FetchArticles.func1()
        github.com/TypicalAM/goread/internal/backend/backend.go:103 +0xf0
github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1.1()
        github.com/charmbracelet/bubbletea@v0.23.2/tea.go:248 +0x30
created by github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1 in goroutine 15
        github.com/charmbracelet/bubbletea@v0.23.2/tea.go:247 +0x10c
```

**Comment by TypicalAM** [comment]
Hey, the date format in the feed is funky (`Jun 11 2019 11:06:55`), so the upstream library that I use to parse the feeds doesn't work for this case. I've created a quick fix over on the `gofeed` repo here: mmcdole/gofeed#234, will fix it in `goread` once it gets merged.

**Comment by sigurd4** [comment]
Same thing happens with the feed After updating from 1.6.5 to 1.7.2, when trying to read the feed `https://www.nrk.no/toppsaker.rss`.

**Comment by TypicalAM** [comment]
Yes, because the upstream issue was merged just 16 hours ago and the release was done yesterday.

**Comment by TypicalAM** [comment]
Solved as of `v1.7.3`, `go install github.com/TypicalAM/goread@latest`
